version : '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${API_DB_USER}
      - POSTGRES_PASSWORD=${API_DB_PASS}
      - POSTGRES_DB=${API_DB_DB}
  api:
    build : ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "1234:80"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - API_DB_USER=${API_DB_USER}
      - API_DB_PASS=${API_DB_PASS}
      - API_DB_DB=${API_DB_DB}
      - API_DB_HOST=${API_DB_HOST}
      - API_DB_PORT=${API_DB_PORT}